# Generated by Django 3.0.8 on 2020-09-14 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vote',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
